name: llana

services:
    llana-prod-test-app:
        container_name: llana-prod-test-app
        image: juicyllama/llana:latest
        ports:
            - "3000:3000"
        environment:
            DATABASE_URI: ${DATABASE_URI}
            JWT_KEY: ${JWT_KEY}
            JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
            HOSTS: ${HOSTS}
            SOFT_DELETE_COLUMN: ${SOFT_DELETE_COLUMN}